app/controllers/api/v1/users_controller.rb, app/controllers/api_controller.rb, config/routes.rb, config/secrets.yml, spec/controllers/api/v1/users_controller_spec.rb, spec/controllers/api_controller_spec.rb
- Adding simple ENV based pre shared API key authentication
- Adding API to add temp users
=> Temp user add api

app/controllers/profile_controller.rb
Users search box now searches for name or email
=> Search users by username/email

app/controllers/vpns_controller.rb, app/views/groups/show.html.slim, app/views/vpns/show.html.slim
fix regression in vpn user management ui
sort users by email
add email for user on vpns page
=> Group users ui change

app/controllers/vpns_controller.rb, app/views/groups/show.html.slim, app/views/layouts/application.html.slim, app/views/vpns/show.html.slim
add blank selection for user, vpn and admin
change vpn users page title
redirect to root on gate sso ico click
add message on adding user to vpn
sort VPNs by name on the group page
=> Gate UI changes

app/controllers/users_controller.rb, app/models/group.rb, app/views/users/show.html.slim, db/migrate/20180104081814_add_product_name_to_users.rb, db/schema.rb, spec/controllers/api/v1/users_controller_spec.rb, spec/controllers/users_controller_spec.rb
- user should be able to add product name to his/her user profile.
=> Add product name info to user profile

api_blueprints/api_v1_user_controller.md, app/controllers/api/v1/users_controller.rb, config/routes.rb, spec/controllers/api/v1/users_controller_spec.rb, spec/controllers/api_controller_spec.rb
- Get user detail by email_id.
=> GetUser Details by email address API

Gemfile, Gemfile.lock, README.md, app/models/user.rb, config/schedule.rb, db/migrate/20180306231200_add_deactivated_at_to_users.rb, db/schema.rb, lib/tasks/users.rake, spec/lib/tasks/users_rake_spec.rb, spec/models/user_spec.rb
Please review, I created a rake task and then schedule it using `whenever` gem. Instead of creating a button, I did the scheduled part directly.
Should I put `whenever --update-crontab` on Dockerfile?
=> Add rake task & schedule it for purging inactive users

app/assets/javascripts/group.coffee, app/assets/javascripts/host_machines.coffee, app/assets/javascripts/users.coffee, app/assets/javascripts/utilities.coffee, app/views/groups/show.html.slim, app/views/host_machines/show.html.slim, app/views/users/show.html.slim
I found this bug when adding admin without waiting autocomplete query to finished.
basically in that scenario gate will save null id. This patch will prevent that from happening by disabling the button until value is not empty
=> Fix bug autocomplete

app/controllers/users_controller.rb, app/models/access_token.rb, app/models/api_resource.rb, app/views/users/show.html.slim, config/routes.rb, db/migrate/20180311161200_rename_token_in_access_tokens.rb, db/schema.rb, spec/controllers/api_resources_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/models/access_token_spec.rb
For user access token
- Only show access token once and stored it as hash
- add 'regenerate' function for token
=> Show user access token only once

app/models/group.rb, app/models/host_machine.rb, db/migrate/20180318083000_create_indexes_to_speedup_nss_controller.rb, db/schema.rb
After doing some profiling, these enhancement should speedup `nss_controller` a bit. I also rewrite `sysadmins` query in `host_machine.rb` to avoid N+1 queries problem.
I understand that we already have redis cache in place, but currently it sets to expire every 5 minutes, so we should increase some actions performance in `nss_controller` (without cache) to acceptable level.
=> Perf optimization

Gemfile, Gemfile.lock, app/controllers/organisations_controller.rb, app/controllers/saml_idp_controller.rb, app/models/organisation.rb, app/validators/email_validator.rb, app/views/organisations/_form.html.slim, app/views/organisations/index.html.slim, app/views/saml_idp/idp/new.html.erb, config/application.rb, config/application.yml.sample, config/initializers/saml_idp.rb, config/routes.rb, db/migrate/20180723175600_update_organisations_for_saml.rb, db/schema.rb, spec/factories/organisations.rb, spec/features/organisations/create_spec.rb, spec/features/organisations/list_spec.rb, spec/features/organisations/setup_saml_spec.rb, spec/features/organisations/update_spec.rb, spec/models/organisation_spec.rb
After the request is merged, below are the things that need to be made sure of
- Run Migration
- Add config value `GATE_URL: 'https://gate.gojek.co.id/'`
=> Saml integration

app/models/user.rb, spec/models/user_spec.rb
Please refer to the following issue https://github.com/gate-sso/gate/issues/122.
This function is being used on User Model line number 132 and 185 to authenticate the user.
=> Fixing null issue with User.get_user_pass_attributes

app/controllers/groups_controller.rb, app/controllers/users_controller.rb, app/views/groups/show.html.slim, app/views/users/show.html.slim
see #133 for detailed fix that went in this PR
=> Issue #133 - Fixing authorization issues on user and group page

app/controllers/api/v1/groups_controller.rb, spec/controllers/api/v1/groups_controller_spec.rb
=> #140 check if the name already taken and return existing group id if any

app/controllers/api/v1/vpns_controller.rb, spec/controllers/api/v1/vpns_controller_spec.rb
(cherry picked from commit e4783f1a376ebc98f39a19b388d1f856f2c397ee)
=> add uuid in vpn creation using v1 api

README.md, app/controllers/users/auth_controller.rb, app/views/layouts/home.html.slim, config/application.yml.sample, config/routes.rb, spec/controllers/users/auth_controller_spec.rb, spec/views/layouts/home.html.slim_spec.rb
This PR will give the option to sign in using the form instead of using google oauth, useful when in development.
cc: @giosakti
=> Add option to use form sign in

app/controllers/admin_controller.rb, app/controllers/api/v1/base_controller.rb, app/controllers/api/v1/groups_controller.rb, app/controllers/api/v1/users_controller.rb, app/controllers/api/v1/vpns_controller.rb, app/controllers/api_resources_controller.rb, app/controllers/application_controller.rb, app/controllers/groups_controller.rb, app/controllers/host_controller.rb, app/controllers/host_machine_groups_controller.rb, app/controllers/host_machines_controller.rb, app/controllers/nss_controller.rb, app/controllers/pings_controller.rb, app/controllers/profile_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users_controller.rb, app/controllers/vpn_domain_name_servers_controller.rb, app/controllers/vpns_controller.rb
Regarding #111 we need to clean up our code to comply `rubocop.yml` setting.
This PR will reduce the number of Rubocop warning in controllers.
@giosakti
=> Cleanup controllers to comply with Rubocop setting

app/controllers/groups_controller.rb, app/models/group.rb, spec/controllers/groups_controller_spec.rb, spec/models/group_spec.rb
Fill group controller spec for add_user, add_group, and index method.
Cleanup related files including the model.
@giosakti
=> Fill group controller spec for add user, add group and index.

.dockerignore, .travis.yml
Current docker image doesn't contain the necessary assets.
@giosakti
=> Publish assets to docker image

.gitignore, README.md, docker-compose.yaml, setup.sh
Add docker-compose for easy development
@giosakti
=> Docker compose for easy development

CHANGELOG.md, app/controllers/groups_controller.rb, app/models/group.rb, app/models/group_association.rb, app/models/user.rb, app/views/groups/show.html.slim, app/views/users/show.html.slim, config/schedule.rb, db/migrate/20190624024930_add_expiration_date_to_group_associations.rb, db/schema.rb, lib/tasks/users.rake, spec/controllers/groups_controller_spec.rb, spec/models/group_association_spec.rb, spec/models/group_spec.rb, spec/models/user_spec.rb, spec/views/groups/show.html.slim_spec.rb
Admin can add a user to group with an expiration date.
Expired membership will be removed by task defined in the scheduler.
Use `whenever --update-crontab` to export scheduler to a cron job.
@giosakti
=> Group membership with expiration date

api_blueprint/hooks/dredd_hooks.rb, api_blueprint/user.apib, app/controllers/api/v1/users_controller.rb, spec/controllers/api/v1/users_controller_spec.rb
good afternoon mas @giosakti 
regarding this #162 , I've solved this problem, you can check my PR
happy weekend
=> Fetch only active user

CHANGELOG.md, app/controllers/api/v1/users_controller.rb, app/controllers/api_resources_controller.rb, app/controllers/host_machines_controller.rb, app/controllers/organisations_controller.rb, app/controllers/users_controller.rb, spec/controllers/api/v1/users_controller_spec.rb, spec/controllers/api_resources_controller_spec.rb, spec/controllers/host_machines_controller_spec.rb, spec/controllers/organisations_controller_spec.rb, spec/controllers/users_controller_spec.rb
Improve access policy for actions on resources including profile, user, api resource, host machine, organisation.
@giosakti
=> Improve access policy on resources

app/models/user.rb, spec/models/user_spec.rb
User deactivated_at should update when the user is deactivated.
@giosakti
=> Deactivate user should set timestamp for deactivated_at

CHANGELOG.md, app/controllers/api/v1/base_controller.rb, app/controllers/api/v1/endpoints_controller.rb, app/controllers/api/v1/users_controller.rb, app/models/endpoint.rb, app/models/group.rb, app/models/group_endpoint.rb, app/models/user.rb, config/routes.rb, db/migrate/20190820070910_create_endpoints.rb, db/migrate/20190820075040_create_group_endpoints.rb, db/migrate/20190820080624_add_foreign_key_ref_on_group_endpoints.rb, db/schema.rb, spec/controllers/api/v1/endpoints_controller_spec.rb, spec/controllers/api/v1/users_controller_spec.rb, spec/factories/endpoints.rb, spec/models/endpoint_spec.rb, spec/models/group_endpoint_spec.rb, spec/models/user_spec.rb
Add endpoints authorization mechanism, user can be given authorization for certain endpoint without admin status.
Endpoints will be owned by groups, to give the user access to endpoint then the user needs to be a member of groups that has the endpoint access.
cc @giosakti
=> Add endpoints authorization mechanism

CHANGELOG.md, app/controllers/groups_controller.rb, app/views/groups/show.html.slim, spec/controllers/groups_controller_spec.rb
Add extra information on group detail such as:
- Email of the group admins
- Users join date to group
@giosakti
=> Extra information on group detail
